# docker-compose.yml

version: '3'
services:
  db:
    image: digitalpatterns/timescaledb:latest
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./postgres/data:/var/lib/postgresql/data/pgdata
      - ./postgres/config/setup-keycloakdb.sh:/docker-entrypoint-initdb.d/004-setup-keycloakdb.sh

  keycloak:
    image: jboss/keycloak:latest
    container_name: keycloak
    restart: on-failure
    command:
      - "-b 0.0.0.0"
      - "-Dkeycloak.import=/opt/jboss/keycloak/realm-export.json"
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: db
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: keycloakPwd
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
      #JDBC_PARAMS: "ssl=true"
    volumes:
      - ./keycloak/realm-export.json:/opt/jboss/keycloak/realm-export.json
    ports:
      - 8080:8080
    depends_on:
      - db

  flyway:
    image: quay.io/ukhomeofficedigital/refdata:latest
    container_name: flyway
    entrypoint: /bin/bash -c /docker/run.sh
    volumes:
      - ./schemas:/schemas
      - ./docker:/docker
    environment:
      - DB_HOSTNAME=db
      - DB_PORT=5432
      - DB_NAME=ref
      - DB_DEFAULT_NAME=postgres
      - FLYWAY_USER=postgres
      - FLYWAY_PASSWORD=password
      - DB_OWNERNAME=dbowner
      - DB_OWNERPASSWORD=dboPwd
      - DB_SCHEMA=public
      - FLYWAY_PLACEHOLDERS_AUTHENTICATORUSER=authuser
      - FLYWAY_PLACEHOLDERS_AUTHENTICATORPASSWORD=authPwd
      - FLYWAY_PLACEHOLDERS_ANONUSER=anonuser
      - FLYWAY_PLACEHOLDERS_READONLYUSER=readonlyuser
      - FLYWAY_PLACEHOLDERS_SERVICEUSER=serviceuser
      - FLYWAY_PLACEHOLDERS_REPORTUSER=reportuser
    depends_on:
      - db

  postgrest:
    image: postgrest/postgrest
    container_name: postgrest
    restart: on-failure
    environment:
      - POSTGREST_NAME=postgrest
      - PGRST_DB_ANON_ROLE=anonuser
      - PGRST_DB_SCHEMA=public
      - PGRST_JWT_AUD=postgrest
      - PGRST_ROLE_CLAIM_KEY=.postgrest
      - PGRST_DB_URI=postgres://authuser:authPwd@db:5432/ref
      - PGRST_SERVER_PROXY_URI=http://127.0.0.1:3000/
      - PGRST_DB_POOL=30
      - PGRST_DB_POOL_TIMEOUT=20
      - PGRST_JWT_SECRET={"kid":"4sYilvPF_brQZ12FMI-Pq03SNIcWhGHDYrTv8eoznPs","kty":"RSA","alg":"RS256","n":"3LmBAoGbVIao_0J9-CUQjDPU4NLrXjV2z1g6QeIYlAXoWPQGM7ZZnTqhghNJFCpDubwUwHu93Eai2vdeBPEPNa5Lsp-UktdkydrflTOIdKGdSXvrTVH5trzpImq8RQocCsgq22gWsZqs8AHXzVYC4axJ4bqsqm1RSs3y7r7PTUd3BJkpMLp2klCMvS1LV0O8Mm_JaGsktSow61z9VTzT6t39CtDhxMwMUUfFKQj6Az11i62eDMaO7OV2dG8ZNFtCjrEIeV4LUlI9-hyBjV-xLf5aftZ35YUwAOvZWCdEBYE2k-kIhMvOpTf9EDGW1O4tZDlp_aPCPYxKAecTlRyzeQ","e":"AQAB"}

    ports:
      - 3000:3000
    depends_on:
      - db
      - flyway


  csv_loader:
    image: quay.io/ukhomeofficedigital/csv_loader:latest
    container_name: csv_loader
    command: "-e docker"
    volumes:
      - ../csv/initial_csvs:/app/csvs/initial
      - ../csv/patch_csvs:/app/csvs/patch
      - ../csv/load_order.yaml:/app/load_order.yaml
    depends_on:
      - db
      - flyway
      - postgrest
