---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{.REFDATA_NAME}}
  namespace: {{.KUBE_NAMESPACE}}
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: "Never"
      containers:
      - name: {{.REFDATA_NAME}}
        image: {{.REFDATA_IMAGE}}:{{.REFDATA_TAG}}
        securityContext:
          runAsUser: 1000
          runAsNonRoot: true
        resources:
          requests:
            memory: "1024Mi"
            cpu: "1000m"
          limits:
            memory: "1024Mi"
            cpu: "1000m"
        env:
          - name: DB_HOSTNAME
            value: "{{.DB_HOSTNAME}}"
          - name: DB_PORT
            value: "{{.DB_PORT}}"
          - name: DB_NAME
            value: "{{.DB_NAME}}"
          - name: DB_DEFAULT_NAME
            value: "{{.DB_DEFAULT_NAME}}"
          - name: DB_OPTIONS
            value: "{{.DB_OPTIONS}}"
          - name: DB_JDBC_OPTIONS
            value: "{{.DB_JDBC_OPTIONS}}"
          - name: FLYWAY_USER
            value: "{{.FLYWAY_USER}}"
          - name: FLYWAY_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{.FLYWAY_PASSWORD}}
                key: flywaypassword
          - name: DB_OWNERNAME
            value: "{{.DB_OWNERNAME}}"
          - name: DB_OWNERPASSWORD
            valueFrom:
              secretKeyRef:
                name: {{.DB_OWNERPASSWORD}}
                key: dbownerpassword
          - name: DB_SCHEMA
            value: "{{.DB_SCHEMA}}"
          - name: FLYWAY_PLACEHOLDERS_AUTHENTICATORUSER
            value: "{{.FLYWAY_PLACEHOLDERS_AUTHENTICATORUSER}}"
          - name: FLYWAY_PLACEHOLDERS_AUTHENTICATORPASSWORD
            valueFrom:
              secretKeyRef:
                name: {{.FLYWAY_PLACEHOLDERS_AUTHENTICATORPASSWORD}}
                key: flywayauthenticatorpassword
          - name: FLYWAY_PLACEHOLDERS_ANONUSER
            value: "{{.FLYWAY_PLACEHOLDERS_ANONUSER}}"
          - name: FLYWAY_PLACEHOLDERS_SERVICEUSER
            value: "{{.FLYWAY_PLACEHOLDERS_SERVICEUSER}}"
          - name: FLYWAY_PLACEHOLDERS_READONLYUSER
            value: "{{.FLYWAY_PLACEHOLDERS_READONLYUSER}}"
