---
apiVersion: v1
kind: Secret
metadata:
  name: {{.REFDATA_NAME}}
type: Opaque
data:
  flywaypassword: "{{.FLYWAY_PASSWORD | b64enc }}"
  dbownerpassword: "{{.DB_OWNERPASSWORD | b64enc }}"
  flywayauthenticatorpassword: "{{.FLYWAY_PLACEHOLDERS_AUTHENTICATORPASSWORD | b64enc }}"
