# docker-compose.yml

version: '3'
services:
  rest:
    image: postgrest/postgrest
    ports:
      - "3000:3000"
    links:
      - db:db
    environment:
      PGRST_DB_URI: postgres://app_user:password@db:5432/ref
      PGRST_DB_SCHEMA: public
      PGRST_DB_ANON_ROLE: app_user
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ref
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: password
  flyway:
    image: flyway/flyway
    command: -url=jdbc:postgresql://db:5432/ref -user=app_user -password=password -connectRetries=60 migrate
    volumes:
      - ./../schemas/reference:/flyway/sql
      - ./../docker:/flyway/conf
    environment:
      FLYWAY_CONFIG_FILES: ./conf/flyway_reference_docker.conf
      FLYWAY_PLACEHOLDERS_SCHEMA: public
      FLYWAY_PLACEHOLDERS_AUTHENTICATORUSER: authenticatorreference
      FLYWAY_PLACEHOLDERS_AUTHENTICATORPASSWORD: auth1234
      FLYWAY_PLACEHOLDERS_ANONUSER: webanon
      FLYWAY_PLACEHOLDERS_SERVICEUSER: servicereference
      FLYWAY_PLACEHOLDERS_READONLYUSER: readonlyreference
    depends_on:
      - db