name: Publish Docker
on:
  push:
    branches:
      - master
jobs:
#  test:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: joschi/setup-jdk@v2
#        with:
#          java-version: 'openjdk11'
#          architecture: 'x64'
#      - name: Grant execute permission for gradlew
#        run: chmod +x gradlew
#      - name: Run tests
#        run: ./gradlew clean test
#      - uses: actions/upload-artifact@v2
#        if: failure()
#        with:
#          name: build
#          path: build/
#          if-no-files-found: ignore

  build:
#    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: linux/arm/v7,linux/arm64/v8,linux/amd64
          tags: "digitalpatterns/flyway-ref-public:latest,digitalpatterns/flyway-ref-public:${{ github.sha }}"
