name: Schema Validation

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  validate:
    runs-on: ubuntu-20.04
    container:
      image: quay.io/ukhomeofficedigital/csv_loader:latest
      options: --user 1001

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Run flyway setup
        run: /flyway/run.sh
        working-directory: /
        env:
          FLYWAY_LOCATIONS_INIT: "filesystem:/__w/RefData/RefData/flyway/schemas/init"
          FLYWAY_INIT_CONF: "/__w/RefData/RefData/flyway/conf/init.conf"
          FLYWAY_LOCATIONS_REFERENCE: "filesystem:/__w/RefData/RefData/flyway/schemas/reference"
          FLYWAY_REFERENCE_CONF: "/__w/RefData/RefData/flyway/conf/reference.conf"

      - name: Run Schema Validation
        run: /validation/validate.py
        env:
          FLYWAY_REFERENCE_CONF: "/__w/RefData/RefData/flyway/conf/reference.conf"
          FLYWAY_LOCATIONS_REFERENCE: "/__w/RefData/RefData/flyway/schemas/reference"
        working-directory: /
